image: mcr.microsoft.com/dotnet/sdk:latest

before_script:
  - 'dotnet restore'

build_bld:
  stage: build
  script:
  - 'dotnet build --no-restore'

test_tst:
  stage: test
  script:
  - 'dotnet test'
